network:
  ethernets:
    eth0:
      addresses:
      - 192.168.1.154/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
        - 192.168.1.1
        search:
        - lan
    eth1:
      dhcp4: true
    eth2:
      dhcp4: true
    eth3:
      dhcp4: true
  version: 2
